<?php

namespace Kregel\Basement\DigitalOcean\Tests;

use Dotenv\Dotenv;
use PHPUnit\Framework\TestCase;

class AbstractTestCase extends TestCase
{
    protected function setUp(): void
    {
        $dotenv = Dotenv::createImmutable(__DIR__ . '/../');
        $dotenv->load();

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
